development:
  base_domain: lvh.me:3000
  google_oauth2: &google_oauth2
    client_id: ""
    client_secret: ""
  mixpanel_token: ""
  slack: &slack
    channel: '#test'
    bot-api-token: ""
  intercom: &intercom
    client_id: ""
    client_secret: ""
  sentry: "https://620638c031fb45fa98198c57f7bd89e2:a621c30ebcd74c6b9779e953176a9011@sentry.io/233277"

test:
  base_domain: lvh.me:4000
  google_oauth2: *google_oauth2
  mixpanel_token: ""
  slack: *slack
  sentry: ""
