name: Deploy To Server

on:
  workflow_dispatch:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Install SSH key to Server
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        name: id_rsa
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        config: |
          host *getcadet.com
            IdentityFile ~/.ssh/id_rsa
            IdentitiesOnly yes
            ForwardAgent yes

    - name: Add ssh-key
      run: |
        eval `ssh-agent -s`
        ssh-add ~/.ssh/id_rsa

    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.4.1
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - name: Deploy to production
      run: |
        bundle exec cap production deploy